Mainapp/urls.py
from django.urls import path 

from . import views

app_name = 'MainApp'

urlpatterns = [
    path('',views.index, name= 'index'),  #Be consistent here, the only path we have here is our home page 
    path('topics',views.topics, name='topics'),
    path('topics/<int:topic_id>/',views.topic, name='topic'),
    path('new_topic',views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/',views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/',views.edit_entry, name='edit_entry'),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Mainapp.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register, name='register')
]

Mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#everytime changes are made here you have to make migrations and migrate

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add= True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text 

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add= True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

Mainapp/forms.py
from django import forms 

from .models import Entry, Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}

Mainapp/views.py
#fuction of the view is to read and write to the database
from django.forms.forms import Form
from django.shortcuts import redirect, render
from .forms import EntryForm, TopicForm
from .models import Topic, Entry
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'MainApp/index.html') #usually a lot but we are being simple, which would involve us evaluating post and gets

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')

    context = {'topics': topics} #the key is what we use in the template, the value is what youre getting from the view.

    return render(request, 'MainApp/topics.html', context) #passing the dictionary to the template
    
@login_required
def topic(request,topic_id):
    topic = Topic.objects.get(id= topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}

    return render(request, 'Mainapp/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()

            return redirect('MainApp:topics')

    context = {'form':form} #allows us to put it on the html skeleton 
    return render(request, 'MainApp/new_topic.html', context)

@login_required
def new_entry(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)

        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('MainApp:topic', topic_id=topic_id)

    context = {'form':form, 'topic':topic}
    return render(request, 'MainApp/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic 

    if request.method != 'POST':
        form = EntryForm(instance=entry) #Tells django which object to pull in  
    else:
        form = EntryForm(instance=entry, data=request.POST) #locking in the new changes
        if form.is_valid():
            form.save()
            return redirect('MainApp:topic', topic_id=topic.id)

    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'MainApp/edit_entry.html', context)

users/views.py
from django.forms.widgets import DateTimeBaseInput
from django.shortcuts import render,redirect
from django.contrib.auth import login 
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request,new_user)
            return redirect('MainApp:index')

    context = {'form':form}
    return render(request, 'registration/register.html', context)

Mainapp/templates/MainApp/base.html
<p>
    <a href="{% url 'MainApp:index' %}">Learning log</a>
    <a href="{% url 'MainApp:topics' %}">Topics</a>
    {% if user.is_authenticated %}
    Hello, {{user.username}}
    <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
    <a href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}

{% endblock content %}

Mainapp/templates/MainApp/edit_entry.html
{% extends "Mainapp/base.html" %}

{% block content %}


<p><a href="{% url 'MainApp:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>

<form action="{% url 'MainApp:edit_entry' entry.id %}" method="post">
    {% csrf_token %}

    {{form.as_p}}
    <button name="submit">save changes</button>

</form>




{% endblock content %}

Mainapp/templates/MainApp/index.html
{% extends "Mainapp/base.html" %}

{% block content %}

<p>Learning Log</p>

<p>Learning log helps you keep track of your
    learning, for any topic you're learning about.
</p>

{% endblock content %}

Mainapp/templates/MainApp/new_entry.html
{% extends "Mainapp/base.html" %}

{% block content %}


<p><a href="{% url 'MainApp:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>

<form action="{% url 'MainApp:new_entry' topic.id %}" method="post">
    {% csrf_token %}

    {{form.as_p}}
    <button name="submit">Add entry</button>

</form>




{% endblock content %}

Mainapp/templates/MainApp/new_topic.html
{% extends "Mainapp/base.html" %}

{% block content %}

<p>Learning Log</p>

<p>Add a new topic:</p>

<form action="{% url 'MainApp:new_topic' %}" method="post">
    {% csrf_token %}

    {{form.as_p}}
    <button name="submit">Add button</button>

</form>




{% endblock content %}

Mainapp/templates/MainApp/topic.html
{% extends "Mainapp/base.html" %}

{% block content %}

<p>Topic: {{ topic }} </p>

<ul>
    {% for e in entries %}
    </li>
    <p>{{e.text|linebreaks }}</p>
    <p>{{e.date_added|date:'M d, H:i'}}</p>
    <p><a href="{% url 'MainApp:edit_entry' e.id%}">Edit entry</a></p>
    </li>


    {% empty %}
    <li> There are no entries for this topic yet </li>
    {% endfor %}
</ul>

<p>
    <a href="{% url 'MainApp:new_entry' topic.id%}"> Add a new entry</a>
</p>
{% endblock content %}

Mainapp/templates/MainApp/topics.html
{% extends "Mainapp/base.html" %}

{% block content %}

<p>Topics</p>
<ul>
    {% for topic in topics %}

    <li>
        <a href="{% url 'MainApp:topic' topic.id%}">{{ topic }} </a>
    </li>
    {% empty %}
    <li> No topics have been added yet.</li>
    {% endfor %}
</ul>
<p>
    <a href="{% url 'MainApp:new_topic' %}">Add a new topic</a>
</p>
{% endblock content %}